version: "3.6"

networks:
  internal-net:
    name: gateway

services:
  nginx:
    image: nginx-proxy
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - gateway
    ports:
      - "80:80"
    networks:
      - internal-net

  gateway:
    image : gateway-native:latest
    container_name: gateway.backend
    build:
      context: .
      dockerfile: ./docker/gateway/native/Dockerfile
    networks:
      - internal-net
